export const GlobalIcons = {
    remove: require('../assets/remove.png'),
    userConfig: require('../assets/userConfig.png'),
    format: require('../assets/format.png'),
    config: require('../assets/config.png'),
    refresh: require('../assets/refresh.png'),
    powerOn: require('../assets/power_1.png'),
    powerOff: require('../assets/power_0.png'),
    wifiOn: require('../assets/wifi_green.png'),
    wifiOff: require('../assets/wifi_white.png'),
    checkboxOn: require('../assets/bool_1.png'),
    checkboxOff: require('../assets/bool_0.png'),
    squareOn: require('../assets/square_1.png'),
    squareOff: require('../assets/square_0.png'),
    wifiLow: require('../assets/wifi_4.png'),
    wifiMedium: require('../assets/wifi_3.png'),
    wifiGood: require('../assets/wifi_2.png'),
    wifiExcelent: require('../assets/wifi_1.png'),
    search: require('../assets/search.png'),
    esprgb_128: require('../assets/esprgb_icon_128.png'),
    esprgb_45: require('../assets/esprgb_icon_45.png'),
    gear: require('../assets/gear.png'),
};